import FooterPage from '@/components/Footer';
import './ui/global.css';
import Navbar from '@/components/Navbar';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <main className="flex flex-col">
        <Navbar />
        {children}
        <FooterPage />
      </main>
      </body>
    </html>
  )
}
